Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,8 +23,17 @@ jobs:
 
       - name: Deploy to EC2
         run: |
-          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
-            whoami
-            ls -ld /hmoe/asher/app/demo
-            pwd
+          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no asher@${{ secrets.SSH_HOST }} << 'EOF'
+            
+            # 디렉토리가 있는지 확인
+            if [ -d "/home/asher/app/demo" ]; then
+              echo "project directory checked."
+              
+              # 프로젝트 폴더 이동
+              cd /home/asher/app/demo
+              pwd
+            else
+              echo "project directory not found!"
+              exit 1
+            fi
           EOF
